[local]
localhost

[mongodb]
mongodb.avkc.online

[redis]
redis.avkc.online

[mysql]
mysql.avkc.online

[rabbitmq]
rabbitmq.avkc.online

[catalogue]
catalogue.avkc.online

[user]
user.avkc.online

[cart]
cart.avkc.online

[shipping]
shipping.avkc.online

[payment]
payment.avkc.online

[frontend]
frontend.avkc.online


