- name: demo on variable
  hosts: localhost
  connection: local
  vars:
    course: ansible
    trainer: siva
    me: chakri
    duration: 150
  tasks:
  - debug:
      msg: "hi iam learning {{course}}, my trainer is {{trainer}} and iam {{me}} duration is {{duration}} HRS"