- name: check number of live sessions
  hosts: local
  connection: local
  vars:
    live_sessions: 6
  tasks:
  - name: is ansible more than 5 sessions
    debug:
      msg: "yes, there are more than 5 live sessions"
    when: live_sessions > 5