- name:  demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, python
    tagMap:
      name: ansible
      project: roboshop
      environment: dev
    tagsList:  [{'key': 'name', 'value': 'ansible'}, {'key': 'project', 'value': 'roboshop'}, {'key': 'environment', 'value': 'dev'}]
    fullname: A V K CHakravarthi
    ip_address: 127.25.56.85
  tasks: 
  - name: convert string to list
    debug:
      msg: "topics are {{topics | split(',') | list}}"

  - name: set default value
    debug:
      msg: "hi {{ greeting | default('good morning')  }}"

  - name: convert map to list
    debug:
      msg: "tagMap is {{ tagMap | dict2items }}"

  - name: convert list to map
    debug:
      msg: "tagsList is {{ tagsList | items2dict }}"

  - name: convert string to uppercase
    debug:
      msg: "full name is {{ fullname | upper }}"

  - name: convert string to lowercase
    debug:
      msg: "full name is {{ fullname | lower }}" 

  - name: check ip address is valid or not 
    debug:
      msg: "ip address is {{ ip_address | ansible.utils.ipv4 }}"   