- name: demo on shell vs commnad
  hosts: local
  connection: local
  tasks:
  - name: command test
    #command: cat /etc/passwd | grep root
    shell: cat /etc/passwd | grep root
    register: result_output

  - name: print result
    debug:
      msg: "{{ result_output}}"