- name: demo on error handling
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exist or not
    command: id roboshop
    register: user_check
    ignore_errors: true

  - name: print user_check
    debug:
      msg: "{{ user_check }}"

  - naem: create user
    command: useradd robishop
    when: user_check.rc !=0