- name: demo on error handling
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: check roboshop user exist or not
    command: id roboshop
    register: user_check
    ignore_errors: true

  - name: print user_check
    debug:
      msg: "{{ user_check }}"

  - name: create user
    command: useradd roboshop
    when: user_check.rc != 0