- name: demo on error handling
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exist or not
    command: id roboshop
    register: user_check
    ignore_error: true

  - name: print user_check
    debug:
      msg: "{{ user_cehck }}"
    