[frontend]
172.31.8.67   ;course="local ansible"

[catalogue]

[user]


[cart]


[roboshop:children]   #group of groups
frontend
catalogue
user
cart

[local]
localhost

[local:vars]
course="ansible"
trainer="siva"
duration="150"
me="chakri"

[frontend:vars]
course="ansible"
trainer="siva"
duration="150"
me="chakri"
